// AUTO-GENERATED BY scripts/sync-controllers.mjs. This stub is overwritten at build time.
import type { WidgetFactory } from '../types';
const controllers: Record<string, WidgetFactory> = {};
export default controllers;